
# Directory to mount torrents in
# torrent_dir = "~/.cache/btbrowse"

# If true, download only the metadata, otherwise download the entire torrent contents automatically
# browse_only = false

# Torrents will self-distruct after this many hours
# hours_to_live = 12
