
# Directory to mount torrents in
# torrent_dir = "~/.cache/btbrowse"

# If false, download the entire torrent contents automatically, otherwise only download files when they are opened
# browse_only = true

# Torrents will self-distruct after this many hours
# hours_to_live = 12
